### ISSUE TITLE
Allow reuse of personal statements

### ISSUE THREAD

**Issue by fofr** [DFE-Digital/apply-for-teacher-training-prototype#143]
A follow-on from https://github.com/DFE-Digital/apply-for-postgraduate-teacher-training-prototype/pull/144

Currently we force users to create a new statement for each provider. This might test fine, and users might be happy to simply copy and paste – perhaps that is an MVP.

If we want to allow reuse it gets a little complex:
- what is the source of the thing being reused
- what happens when that source is removed (eg course removed)
- if we don't tie to a course we'd need another way to identify, like a statement name, which feels awkward
- when there are 3 courses and 2 other statements, if they want to reuse they need a choice for which one they reuse
- when clicking through to a statement that's reusing another one, what should users see?
- how does a user stop reusing a statement, eg they decide to customise instead
- does duplication make more sense than a shared version? typos and changes would need to be updated in multiple places – that is true with copying and pasting already

An example of what this might look like:
![Screen Shot 2019-09-03 at 16 15 30](https://user-images.githubusercontent.com/319055/64262760-80e97080-cf26-11e9-99fb-2038683fd383.png)

A quick branch to illustrate without logic:
https://github.com/DFE-Digital/apply-for-postgraduate-teacher-training-prototype/compare/copy-existing-statements

**Comment by paulrobertlloyd** [comment]
[Research on tailoring personal statements was conducted in July 2020](https://docs.google.com/presentation/d/1FLHOnLTVtxVjzo8dZEoSuqFDmjMMWdGRGVxtmMBFzX0). While there are some ideas where we could take this in the future, the need was not as pressing as we first thought.
