### ISSUE TITLE
Add page for applying on UCAS after course choices

### ISSUE THREAD

**Issue by laurahermionetennant92** [DFE-Digital/apply-for-teacher-training-prototype#229]
Can this be moved to after course selection (because the application is course specific not provider specific and some providers will have courses that are opted in and opted out. 
![Screenshot 2019-10-15 at 16 30 59](https://user-images.githubusercontent.com/38726669/66846187-58af5180-ef69-11e9-8d6e-d8ff7e300efb.png)

**Comment by fofr** [comment]
Updating issue to reflect that we need a new page after course selection, as well as one after provider choice.
