### ISSUE TITLE
Post-decline page

### ISSUE THREAD

**Issue by laurahermionetennant92** [DFE-Digital/apply-for-teacher-training-prototype#285]
In the decision flow there will be a state in the DBD stage when
1. one offer has been declined, and one offer is still waiting to be accepted
2. and another state when all offers have either been declined, or the candidate has been rejected. We need different end content for both.

First instance [Candidate has declined one offer, another offer(s) is waiting to be accepted]

Responding to training providers
Now all of your training providers have reached a decision, you have 10 working days to respond to any offers.

If you don’t respond, all your applications will be automatically withdrawn.

Remember:

you can only accept one offer, across both Apply for teacher training and UCAS teacher training
if you fail to respond, or you decline all your offers, you can still apply to other courses in future
you can get advice about future applications by registering with Get into Teaching

Second instance [Candidate has been rejected and has declined other offers]

Getting help with your onward application journey
To apply to more courses this year, you’ll need to go through UCAS Teacher Training.
First, search for courses through Find postgraduate teacher training courses. You'll then be guided through to UCAS.
Register with Get into Teaching for advice and support.

**Comment by paulrobertlloyd** [comment]
I think we should review where all our guidance sits, because it’s spread across a few different places at the moment. Now we have the bones of an end-to-end journey hooked up (and an improved means of mocking up different application states and phases — I’ll show you), we can review this more holistically.
