### ISSUE TITLE
Add another as radio buttons

### ISSUE THREAD

**Issue by adamsilver** [DFE-Digital/apply-for-teacher-training-prototype#288]
Currently, at the end of adding a thing, the UI looks like this:

![image](https://user-images.githubusercontent.com/37163/68401747-2cef4800-0172-11ea-8386-888f1a0b46b9.png)

GOV.UK Design System guidance says:

> Avoid using multiple default buttons on a single page. Having more than one main call to action reduces their impact, and makes it harder for users to know what to do next.

Even though we have 1 primary and 1 secondary action, it's still more prone to error (like picking the wrong button or missing one of the buttons entirely), generally speaking.

One way to avoid the chance of error is to ask users whether they'd like to add another or not as radio buttons. 

The MOJ Design System suggests this for the upload a file flow (which is based on the HO Design System):
https://moj-design-system.herokuapp.com/patterns/upload-files

![image](https://user-images.githubusercontent.com/37163/68402342-1695bc00-0173-11ea-886b-c326381fa926.png)

And HMRC has a similar thing to here:
https://hmrc.github.io/assets-frontend/patterns/add-to-a-list/index.html

![image](https://user-images.githubusercontent.com/37163/68402364-1f868d80-0173-11ea-9086-7022e204911d.png)

I'm wondering out loud if there's a way to remove the need for the optional ‘I've finished’ checkbox too.

**Comment by frankieroberto** [comment]
@adamsilver I think we can close this for now, as we've gone with the alternative approach of moving the "Add another" button to the top of the page.

Another approach we could consider in future is removing the "I have completed this section" checkbox feature, which would remove the need for the Continue button – we could just have a green "Add another" button and a link back to the application summary.  We would have to be confident that auto-marking sections as complete would work ok though.
